# Generated by Django 4.1.7 on 2023-04-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project10app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
